### ISSUE TITLE
GWTPolymer Elements 1.7.0 : Polymer.setGwtBowerLocation(""); missing

### ISSUE THREAD

**Issue by GG200989** [vaadin/gwt-api-generator#73] opened 2016-12-13 09:23 UTC
Can you please help me with generating gwt widget out of my custom web component?
I tried using 
@JsType(isNative=true)
public interface MyAppElement {
	
	@JsOverlay public static final String TAG = "mba-app";
   // @JsOverlay public static final String SRC = "my-app/mba-app.html";
    
    @JsOverlay public static final String SRC = "my-app/mba-app.html";

}

but it is unable to find my html element.

Thanks,
Gaurav

**Comment by GG200989** [comment] 2016-12-13 11:19
Also, can you give link to generate gwt element/widgets using my custom web components, one I can see as gwt-api-generator. any example would be very helpful.

Thanks,
Gaurav

**Comment by manolo** [comment] 2017-02-01 11:49
Have your read  https://github.com/vaadin/gwt-api-generator#using-your-own-web-components-in-your-app ?

Also you can take a look to this demo example to see how to use 3rd party elements not included with the gwt-polymer-elements bundle. https://github.com/vaadin/gwt-polymer-elements/blob/master/demo/

Bug basically, you only have to install your element locally and run the generator.

```
$ bower install github_user/element-name#master
$ gwt-api-generator
```

Closing this issue since it's not a bug, feel free to ask here or in gitter vaadin elements chat

**Closed by manolo** 2017-02-01 11:49 UTC
